apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
#address: 0.0.0.0
address: {{ inventory_hostname }}
#authentication:
#  anonymous:
#    enabled: false
#  webhook:
#    cacheTTL: 2m0s
#    enabled: true
#  x509:
#    clientCAFile: /etc/kubernetes/secret/certs/k8sca/k8sca.crt
#authorization:
#  mode: Webhook
#  webhook:
#    cacheAuthorizedTTL: 5m0s
#    cacheUnauthorizedTTL: 30s
staticPodPath: /etc/kubernetes/manifests
clusterDNS:
- 10.1.0.2
clusterDomain: cluster.local.
#cgroupDriver: cgroupfs
#cgroupsPerQOS: true
#nodeLeaseDurationSeconds: 40
#nodeStatusReportFrequency: 5s
#nodeStatusUpdateFrequency: 5s
port: 10250
#imageGCHighThresholdPercent: 100
#imageGCLowThresholdPercent: 80
#evictionHard:
#  imagefs.available: 0%
#  memory.available: 500Mi
#  nodefs.available: 0%
#  nodefs.inodesFree: 5%
#configMapAndSecretChangeDetectionStrategy: Watch
#containerLogMaxFiles: 5
#containerLogMaxSize: 10Mi
#contentType: application/vnd.kubernetes.protobuf
#cpuCFSQuota: true
#cpuCFSQuotaPeriod: 100ms
#cpuManagerPolicy: none
#cpuManagerReconcilePeriod: 10s
#enableControllerAttachDetach: true
#enableDebuggingHandlers: true
#enforceNodeAllocatable:
#- pods
#eventBurst: 10
#eventRecordQPS: 5
#evictionPressureTransitionPeriod: 5m0s
failSwapOn: true
#fileCheckFrequency: 20s
#hairpinMode: promiscuous-bridge
#healthzBindAddress: 127.0.0.1
#healthzPort: 10248
#httpCheckFrequency: 20s
#imageMinimumGCAge: 2m0s
#iptablesDropBit: 15
#iptablesMasqueradeBit: 14
#kubeAPIBurst: 100
#kubeAPIQPS: 50
#makeIPTablesUtilChains: true
#maxOpenFiles: 1000000
#maxPods: 110
#oomScoreAdj: -999
#podPidsLimit: -1
#registryBurst: 20
#registryPullQPS: 5
#resolvConf: /etc/resolv.conf
#rotateCertificates: true
#runtimeRequestTimeout: 2m0s
#serializeImagePulls: true
#streamingConnectionIdleTimeout: 4h0m0s
#syncFrequency: 1m0s
#topologyManagerPolicy: none
#volumeStatsAggPeriod: 1m0s
